python -m trip_planner --add --name "Roman Forum"
python -m trip_planner --add --name "Vatican City"
python -m trip_planner --add --name "Trevi Fountain"
python -m trip_planner --add --name "Colosseum"
python -m trip_planner --add --name "Pantheon"
